#!/bin/bash

PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin

if [ -f /etc/redhat-release ];
then
  if [ -n "$(which needs-restarting)" ];
  then
    services=$(needs-restarting &> >(grep -viE 'Failed to read PID') | wc -l)
    case $services in
      [0]*)
        echo "OK - $services services need to be restarted"
        exit 0
        ;;

      *)
        echo "CRITICAL - $services services need to be restarted"
        exit 2
        ;;
    esac
  else
    echo "UNKNOWN - 'needs-restarting' binary not found. Make sure yum-utils is installed."
    exit 3
  fi

elif [ -f /etc/debian_version ];
then
  if [ -n "$(which checkrestart)" ];
  then
    services=$(checkrestart | grep -iE ^found | head -1 | sed -e 's/^Found\ //g' | sed -e 's/\ processes\ .*//g')
    case $services in
      [0]*)
        echo "OK - $services services need to be restarted"
        exit 0
        ;;

      *)
        echo "CRITICAL - $services services need to be restarted"
        exit 2
        ;;
    esac
  else
    echo $?
    echo "UNKNOWN - 'checkrestart' binary not found. Make sure debian-goodies is installed."
    exit 3
  fi

else
  echo "UNKNOWN - operatingsystem not supported"
fi
